### ISSUE TITLE
server-bootstrap.php PHP Fatal error

### ISSUE THREAD

**Issue by nichedevelopment** [CESNET/pakiti-server#187]
Setting up a new server, and have never installed or used pakiti3 before. When following the install instructions in pakiti-server v3.1.1, after running 'php initDB.php' successfully, I then ran 'server-bootstrap.php' script and the result is a PHP Fatal error, which in turn leaves the VDS's having only RHEL 6, 7, 8, Debian Security and Debian LTS Security with 3549, 4181, 3278, 0 and 0 CVEs respectively (no CVEs for either Debian VDS). The output of the command is:

./server-bootstrap.php
Added vulnerability descriptions for RHEL 6.
Added vulnerability descriptions for RHEL 7.
Added vulnerability descriptions for RHEL 8.
Added vulnerability descriptions for Debian Security.
Added vulnerability descriptions for Debian LTS Security.
Downloading all vulnerability definitions (be patient) ...PHP Fatal error:  Uncaught Error: Access to undeclared static property: Config::$DEBIAN_IGNORED_VERSIONS in /var/www/pakiti-server/src/modules/vds/sources/CveSubSources/Debian.php:212
Stack trace:
#0 /var/www/pakiti-server/src/modules/vds/lib/SubSource.php(223): Debian->processAdvisories()
#1 /var/www/pakiti-server/src/modules/vds/sources/CveSource.php(47): SubSource->retrieveVulnerabilities()
#2 /var/www/pakiti-server/src/modules/vds/VdsModule.php(30): CveSource->retrieveVulnerabilities()
#3 /var/www/pakiti-server/install/server-bootstrap.php(85): VdsModule->synchronize()
#4 {main}
thrown in /var/www/pakiti-server/src/modules/vds/sources/CveSubSources/Debian.php on line 212

Any assistance in resolving this issue would be greatly appreciated, as we are moving away from our Red Hat Satellite and CentOS Spacewalk repositories for our Linux servers as we migrate to Debian.

Thanks!
David

**Comment by aurelienlaurendon** [comment]
I have the same problem with an install in Ubuntun 24.04 LTS.
Did you solve this ?
Regards,
Aurélien

**Comment by HavrilaJ** [comment]
What do you have in /etc/pakiti/Config.php? Because if your config extends class DefaultConfig then there you can find property on line 127 $DEBIAN_IGNORED_VERSIONS.
